// Code generated by Slice Machine. DO NOT EDIT.

import Cathelijne from "./Cathelijne/index.svelte";
import Squad from "./Squad/index.svelte";

export const components = {
  cath: Cathelijne,
  squad: Squad,
};
