// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CardDocumentDataSlicesSlice = MemberSlice;

/**
 * Content for Member documents
 */
interface CardDocumentData {
  /**
   * Name field in *Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Age field in *Member*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: card.age
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  age: prismic.NumberField;

  /**
   * Hobbys field in *Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card.hobbys
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hobbys: prismic.RichTextField;

  /**
   * Picture field in *Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Member*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: card.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CardDocumentDataSlicesSlice>;
}

/**
 * Member document from Prismic
 *
 * - **API ID**: `card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<CardDocumentData>, "card", Lang>;

type SquadDocumentDataSlicesSlice = never;

/**
 * Content for Squad documents
 */
interface SquadDocumentData {
  /**
   * Title field in *Squad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Member field in *Squad*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: squad.member
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  member: prismic.ContentRelationshipField<"card">;

  /**
   * Slice Zone field in *Squad*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: squad.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SquadDocumentDataSlicesSlice>;
}

/**
 * Squad document from Prismic
 *
 * - **API ID**: `squad`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SquadDocumentData>, "squad", Lang>;

type TribeDocumentDataSlicesSlice = never;

/**
 * Content for Tribe documents
 */
interface TribeDocumentData {
  /**
   * Title field in *Tribe*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Squad field in *Tribe*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe.squad
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  squad: prismic.ContentRelationshipField<"squad">;

  /**
   * Slice Zone field in *Tribe*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TribeDocumentDataSlicesSlice>;
}

/**
 * Tribe document from Prismic
 *
 * - **API ID**: `tribe`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TribeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TribeDocumentData>, "tribe", Lang>;

export type AllDocumentTypes = CardDocument | SquadDocument | TribeDocument;

/**
 * Default variation for Member Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Member*
 */
type MemberSliceVariation = MemberSliceDefault;

/**
 * Member Shared Slice
 *
 * - **API ID**: `member`
 * - **Description**: Member
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberSlice = prismic.SharedSlice<"member", MemberSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CardDocument,
      CardDocumentData,
      CardDocumentDataSlicesSlice,
      SquadDocument,
      SquadDocumentData,
      SquadDocumentDataSlicesSlice,
      TribeDocument,
      TribeDocumentData,
      TribeDocumentDataSlicesSlice,
      AllDocumentTypes,
      MemberSlice,
      MemberSliceVariation,
      MemberSliceDefault,
    };
  }
}
