// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CardDocumentDataSlicesSlice = never;

/**
 * Content for Member documents
 */
interface CardDocumentData {
  /**
   * Name field in *Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Age field in *Member*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: card.age
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  age: prismic.NumberField;

  /**
   * Hobbys field in *Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card.hobbys
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hobbys: prismic.RichTextField;

  /**
   * Picture field in *Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Github field in *Member*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card.github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkField;

  /**
   * Slice Zone field in *Member*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: card.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CardDocumentDataSlicesSlice>;
}

/**
 * Member document from Prismic
 *
 * - **API ID**: `card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<CardDocumentData>, "card", Lang>;

type SquadDocumentDataSlicesSlice = never;

/**
 * Content for Squad documents
 */
interface SquadDocumentData {
  /**
   * Title field in *Squad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Member field in *Squad*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: squad.member
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  member: prismic.ContentRelationshipField<"card">;

  /**
   * Slice Zone field in *Squad*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: squad.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SquadDocumentDataSlicesSlice>;
}

/**
 * Squad document from Prismic
 *
 * - **API ID**: `squad`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SquadDocumentData>, "squad", Lang>;

type TribeDocumentDataSlicesSlice = SquadSlice;

/**
 * Content for Tribe documents
 */
interface TribeDocumentData {
  /**
   * Title field in *Tribe*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Squad field in *Tribe*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe.squad
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  squad: prismic.ContentRelationshipField<"squad">;

  /**
   * Slice Zone field in *Tribe*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TribeDocumentDataSlicesSlice>;
}

/**
 * Tribe document from Prismic
 *
 * - **API ID**: `tribe`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TribeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TribeDocumentData>, "tribe", Lang>;

export type AllDocumentTypes = CardDocument | SquadDocument | TribeDocument;

/**
 * Primary content in *Cathelijne → Primary*
 */
export interface CathSliceDefaultPrimary {
  /**
   * Name field in *Cathelijne → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cath.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Age field in *Cathelijne → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cath.primary.age
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  age: prismic.NumberField;

  /**
   * hobbys field in *Cathelijne → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cath.primary.hobbys
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hobbys: prismic.RichTextField;

  /**
   * Picture field in *Cathelijne → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cath.primary.picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Github field in *Cathelijne → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: cath.primary.github
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkToMediaField;
}

/**
 * Default variation for Cathelijne Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CathSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CathSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cathelijne*
 */
type CathSliceVariation = CathSliceDefault;

/**
 * Cathelijne Shared Slice
 *
 * - **API ID**: `cath`
 * - **Description**: Cath
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CathSlice = prismic.SharedSlice<"cath", CathSliceVariation>;

/**
 * Default variation for Squad Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Squad*
 */
type SquadSliceVariation = SquadSliceDefault;

/**
 * Squad Shared Slice
 *
 * - **API ID**: `squad`
 * - **Description**: Squad
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadSlice = prismic.SharedSlice<"squad", SquadSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CardDocument,
      CardDocumentData,
      CardDocumentDataSlicesSlice,
      SquadDocument,
      SquadDocumentData,
      SquadDocumentDataSlicesSlice,
      TribeDocument,
      TribeDocumentData,
      TribeDocumentDataSlicesSlice,
      AllDocumentTypes,
      CathSlice,
      CathSliceDefaultPrimary,
      CathSliceVariation,
      CathSliceDefault,
      SquadSlice,
      SquadSliceVariation,
      SquadSliceDefault,
    };
  }
}
